unleashed: Fix gp/sp/tp, and PTE dependecy
It looks on real hardware, without adding fence(rw, rw) to the
gp/sp/tp and PTE updates, the follow-up usage of gp, sp, tp and MMU
mapping may go wrong. The following cases are observed:
Bug 1:
Observed during SBI initialization, could fail at any point (may
related to sp):
~~~~~~~~~~~~~~~~~~~~
Platform Name          : SiFive Freedom U540
Platform HART Features : RV64ACIMSU
Platform Max HARTs     : 1
Current Hart           : 1
Current Thread Pointer : 0x0000000080025e00
Current Thread Stack   : 0x0000000080025000 - 0x0000000080026000
Firmware Base          : 0x80000000
Firmware Size          : 2097304 KB
Runtime SBI Version    : 0.1

sbi_trap_error: hart1: illegal instruction handler failed (error -95)
sbi_trap_error: hart1: mcause=0x0000000000000002 mtval=0x00000000ffffffff
sbi_trap_error: hart1: mepc=0x0000000080001900 mstatus=0x8000000a00007800
sbi_trap_error: hart1: ra=0x0000000080001c4c sp=0x0000000080025c50
sbi_trap_error: hart1: gp=0x0000000080019a50 tp=0x0000000080025e00
sbi_trap_error: hart1: s0=0x0000000000000000 s1=0x0000000080023370
sbi_trap_error: hart1: a0=0xffffffffe0000000 a1=0x0000000080025d08
sbi_trap_error: hart1: a2=0x0000000080025cf8 a3=0x0000000080025d00
sbi_trap_error: hart1: a4=0x000000001fffffff a5=0xffffffffe0000000
sbi_trap_error: hart1: a6=0x0000000000000001 a7=0x0000000000000001
sbi_trap_error: hart1: s2=0x609a164c0be026dd s3=0x0000000000000000
sbi_trap_error: hart1: s4=0x0000000000000000 s5=0x0000000000000000
sbi_trap_error: hart1: s6=0x0000000000000001 s7=0x0000000000000001
sbi_trap_error: hart1: s8=0x0000000000000000 s9=0x0000000000000000
sbi_trap_error: hart1: s10=0x0000000000000000 s11=0x0000000000000000
sbi_trap_error: hart1: t0=0x0000000080019020 t1=0x0000000000000000
sbi_trap_error: hart1: t2=0x0000000000000001 t3=0x0000000080026000
sbi_trap_error: hart1: t4=0x0000000000000000 t5=0x0000000000000000
sbi_trap_error: hart1: t6=0x0000000000000000
~~~~~~~~~~~~~~~~~~~~
The example failure is against a sd to sp instruction in an entry
point of ctz:
80001900: 00a13423                sd      a0,8(sp)

Bug 2:
The bug can be observed after enabling MMU.
~~~~~~~~~~~~~~~~~~~~
BPGT_PGTABLE_LEVELS=2
PGTABLE_LEVELS=3
Oops - unknown exception at         8000ea84.
 epc:         8000ea84 ra :         8000b19c sp :         80024f78
 gp :         80019a50 tp :         80024ff8 t0 :          1800000
 t1 :                0 t2 :                1 s0 :         80023370
 s1 :         80023370 a0 :         80000000 a1 :            26000
 a2 :         80019148 a3 :         80000000 a4 :         80026000
 a5 :         80000000 a6 :                0 a7 :                1
 s2 : 609a165e0be026d5 s3 :                0 s4 :                0
 s5 :                0 s6 :                1 s7 :                1
 s8 :                0 s9 :                0 s10:                0
 s11:                0 t3 :         80026000 t4 :                0
 t5 :                0 t6 :                0
status:        200000100 badaddr:         80000010 cause:                f
~~~~~~~~~~~~~~~~~~~~
This is likely caused by gp related usage, when a gp based linker
symbol is passed to page_alloc_init().
8000e8a5: 00e7b823                sd      a4,16(a5) # fffffffffffff010 <__end+0xffffffff7ffd9010>

Bug 3:
Happens during fixmap initialization, when mapped PxE is cleared
in memset, illegal store or AMO is observed. This is likely related
to the tlb flush.

However adding fence(rw, rw) only lowers down the bug reproduce
ratio, it can still occur occasionally.

In order to ensure M-mode code has right priviledge, this patch
cleans up MPRV when M-mode is entered.

This patch also sorts mapping console output to the following
style:
~~~~~~~~~~~~~~~~~~~~
Early  MAP: 0000000080000000 - 0000000080026000
FIXMAP: 0000000010000000 -> ffffffffffffd000: PRCI
FIXMAP: 0000000010060000 -> ffffffffffffc000: GPIO
FIXMAP: 0000000010010000 -> ffffffffffffb000: UART0
LOWMAP: 0000000080000000 -> 0000000080000000: 0000000000017000
LOWMAP: 0000000080017000 -> 0000000080017000: 0000000000002000
LOWMAP: 0000000080019000 -> 0000000080019000: 000000000000b000
LOWMAP: 0000000080024000 -> 0000000080024000: 0000000000001000
LOWMAP: 0000000080026000 -> 0000000080026000: 00000001fffda000
reserved: 0000000080000000 - 0000000080025fff
reserved: 000000027fffe000 - 000000027fffffff
memory: 0000000080026000 - 000000027fffe000
~~~~~~~~~~~~~~~~~~~~
So that the mapping information is more comprehensive.

Signed-off-by: Lv Zheng <zhenglv@hotmail.com>